name: quran_life_muslim
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_inappwebview: ^6.1.5
  flutter_qiblah: ^3.0.4
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.2
  flutter_launcher_icons: ^0.12.0
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.2.18
  flutter_native_timezone: ^2.0.0
  geolocator: ^13.0.1
  http: ^1.3.0
  hijri: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.1
  permission_handler: ^11.3.1
  rxdart: ^0.28.0

flutter_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/app-icon.png"
  min_sdk_android: 19

flutter_native_splash:
  image: 'assets/icons/app-icon.png'
  color: "#FFFFFF"
  android: true
  ios: true
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/fonts/
    - assets/sounds/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
#          style: italic

    - family: Reem_Kufi
      fonts:
        - asset: assets/fonts/Reem_Kufi/ReemKufiFun-VariableFont_wght.ttf

    - family: Uthmanic
      fonts:
        - asset: assets/fonts/Uthmanic/uthmanic_hafs_v22.ttf
        - asset: assets/fonts/Uthmanic/UthmanicHafs_V22.ttf

flutter_intl:
  enabled: true